// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ4h_6mvD9n1oCUm4UgVTFXeMSnghofUs',
    appId: '1:314789929219:web:d7c1b077256a37002ec936',
    messagingSenderId: '314789929219',
    projectId: 'moblieapp-7b7ff',
    authDomain: 'moblieapp-7b7ff.firebaseapp.com',
    storageBucket: 'moblieapp-7b7ff.firebasestorage.app',
    measurementId: 'G-81WQ0Z6B67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyznWuMSenuysJHq6zO-qgM0y9HzMICfk',
    appId: '1:314789929219:android:4783219288bd783a2ec936',
    messagingSenderId: '314789929219',
    projectId: 'moblieapp-7b7ff',
    storageBucket: 'moblieapp-7b7ff.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1A1tjVS_sfrqVT73BAhfayrNSKOaMGRo',
    appId: '1:314789929219:ios:3cdc9734a5743ffb2ec936',
    messagingSenderId: '314789929219',
    projectId: 'moblieapp-7b7ff',
    storageBucket: 'moblieapp-7b7ff.firebasestorage.app',
    iosBundleId: 'com.example.helloApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1A1tjVS_sfrqVT73BAhfayrNSKOaMGRo',
    appId: '1:314789929219:ios:3cdc9734a5743ffb2ec936',
    messagingSenderId: '314789929219',
    projectId: 'moblieapp-7b7ff',
    storageBucket: 'moblieapp-7b7ff.firebasestorage.app',
    iosBundleId: 'com.example.helloApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ4h_6mvD9n1oCUm4UgVTFXeMSnghofUs',
    appId: '1:314789929219:web:47d14ef4d0feaa4f2ec936',
    messagingSenderId: '314789929219',
    projectId: 'moblieapp-7b7ff',
    authDomain: 'moblieapp-7b7ff.firebaseapp.com',
    storageBucket: 'moblieapp-7b7ff.firebasestorage.app',
    measurementId: 'G-YPRWXMNP2P',
  );
}
